---
- name: Change user password using ansible account
  hosts: '{{ target }}'
  become: true
  remote_user: ansible
  vars_prompt:
    - name: username
      prompt: 'Enter the user you want to change the password for'
      private: no
    - name: password
      prompt: 'Enter the password you want to set for the user'
  vars_files:
    - variables/password_salt.yml
  tasks:
    - name: Check user exists on the remote host
      ansible.builtin.getent:
        database: passwd
        key: "{{ username }}"
    - name: Change user password to supplied one
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', salt) }}"
        state: present
